######################################################################
# Automatically generated by qmake (3.1) Sun Nov 26 01:17:38 2023
######################################################################

TEMPLATE = app
TARGET = weather
INCLUDEPATH += .

QT += core gui widgets qml quick network multimedia svg

CONFIG += c++11
# Input 
SOURCES += weather.cpp

